version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - parser
  app:
    build:
      args:
        user: alovega
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: news-parser
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - parser
  db:
    image: mysql:5.7
    container_name: parser_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks: 
      - parser

  nginx:
    image: nginx:1.17-alpine
    container_name: parser-nginx
    restart: unless-stopped
    ports: 
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - parser
      
networks:
  parser:
    driver: bridge

